<?php

namespace BH3Bundle\Repository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllNews()
    {
        $qb = $this->createQueryBuilder('a')
            ->orderBy('a.date', 'DESC');
        
        return $qb->getQuery()->getResult();
    }
}
