bh3:
    resource: "@BH3Bundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"

fos_user_registration:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"

fos_user_new_password:
    path: /newpassword
    defaults: { _controller: FOSUserBundle:Resetting:request }

fos_user_register:
    path: /register
    defaults: { _controller: FOSUserBundle:Registration:register }
