# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
    
    role_hierarchy:
        ROLE_REDACTEUR: ROLE_USER
        ROLE_MANAGER: ROLE_USER
        ROLE_ADMIN: [ROLE_USER, ROLE_REDACTEUR, ROLE_MANAGER]
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout: true
            anonymous: true
    
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: [ROLE_MANAGER, ROLE_REDACTEUR] }
        - { path: ^/admin/news, role: ROLE_REDACTEUR }
        - { path: ^/admin/membres, role: ROLE_MANAGER }
        - { path: ^/admin/rosters, role: ROLE_MANAGER }
        - { path: ^/admin/palmares, role: ROLE_MANAGER }
        - { path: ^/admin/partenaires, role: ROLE_ADMIN }
        - { path: ^/admin/messagerie, role: ROLE_ADMIN }
        - { path: ^/admin/admins, role: ROLE_SUPER_ADMIN }
        